In [2]:
import csv
import pandas as pd

In [3]:
women_CEOs_path = "2019_WomenCEO_list.csv"
women_CEOs = pd.read_csv(women_CEOs_path)
women_CEOs

,CEO,Company,2019 Fortune 500 ranking,effective date as CEO,Ticker Symbol (NYS/NASDAQ)
0,Laura Alber,Williams-Sonoma,495,5/1/10,WSM
1,Beth E. Mooney,KeyBank,413,5/1/11,KEY
2,Tricia Griffith,Progressive Corporation,99,7/1/16,PGR
3,Ginni Rometty[3],IBM,38,1/1/12,IBM
4,Safra A. Catz,Oracle Corporation,81,9/18/14,ORCL
5,Marillyn Hewson[4],Lockheed Martin,60,1/1/13,LMT
6,Phebe Novakovic,General Dynamics,92,1/20/13,GD
7,Mary Dillon,Ulta Beauty,449,6/1/13,ULTA
8,Mary Barra,General Motors,13,1/15/14,GM
9,Barbara Rentler,Ross Stores,209,6/1/14,ROST